import { Component, computed, inject, signal } from '@angular/core';
import { HlmButtonImports } from '@ui/button';
import { CostingState } from './costing-state';
import { CostPart, CostProduct, CostResource, CostResourceType, CostTemplate } from './costing.models';
type Tab='products'|'resources'|'parts'|'templates'|'simulator'; type Editor='resource'|'part'|'template'|'product'|null;
@Component({selector:'app-costing',imports:[...HlmButtonImports],templateUrl:'./costing.html'})
export class Costing {
 protected readonly state=inject(CostingState); protected readonly tab=signal<Tab>('products'); protected readonly editor=signal<Editor>(null); protected readonly error=signal('');
 protected readonly tabs:{id:Tab;label:string}[]=[{id:'products',label:'Productos costeados'},{id:'templates',label:'Plantillas'},{id:'parts',label:'Partidas / APU'},{id:'resources',label:'Recursos y precios'},{id:'simulator',label:'Simulador'}];
 protected readonly selectedProductId=signal<string|null>(null); protected readonly selectedProduct=computed(()=>this.selectedProductId()?this.state.product(this.selectedProductId()!):undefined);
 protected resourceDraft=signal<CostResource|null>(null); protected partDraft=signal<CostPart|null>(null); protected templateDraft=signal<CostTemplate|null>(null); protected productDraft=signal<CostProduct|null>(null);
 protected readonly simResource=signal('r3'); protected readonly simPct=signal(8); protected readonly productsWithIncrease=computed(()=>this.state.summaries().filter(x=>x.variationPct>0).length);
 protected readonly simulation=computed(()=>this.state.affectedProducts(this.simResource()).map(product=>{const current=this.state.productCost(product),r=this.state.resource(this.simResource());if(!r)return{product,current,simulated:current,impact:0};const simulated=this.state.productCostWithOverride(product,r.id,r.currentCost*(1+this.simPct()/100));return{product,current,simulated,impact:current?(simulated-current)/current*100:0};}));
 protected money(v:number){return v.toLocaleString('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2});} protected templateName(id:string){return this.state.template(id)?.name??id;} protected resourceName(id:string){return this.state.resource(id)?.name??id;} protected resourceUnit(id:string){return this.state.resource(id)?.unit??'';} protected resourceCost(id:string){return this.state.resource(id)?.currentCost??0;} protected typeLabel(t:CostResourceType){return({material:'Material',labor:'Mano de obra',service:'Servicio',equipment:'Equipo'})[t];} protected partLabel(id:string){const p=this.state.parts().find(x=>x.id===id);return p?`${p.code} · ${p.name}`:id;}
 protected asValue(e:Event){return(e.target as HTMLInputElement).value;} protected asNumber(e:Event){return Number((e.target as HTMLInputElement).value)||0;} protected checked(e:Event){return(e.target as HTMLInputElement).checked;} protected changeCost(id:string,e:Event){this.state.updateResourceCost(id,this.asNumber(e));} protected openProduct(id:string){this.selectedProductId.set(id);} protected productSummary(p:CostProduct){return this.state.summary(p);} protected productParts(p:CostProduct){const t=this.state.template(p.templateId);return this.state.parts().filter(x=>t?.partIds.includes(x.id));} protected partCost(product:CostProduct,id:string){const p=this.state.parts().find(x=>x.id===id);return p?.lines.reduce((s,l)=>s+this.state.lineCost(product,l.resourceId,l.quantity,l.wastePct),0)??0;} protected parameterEntries(p:CostProduct){return Object.entries(p.parameters);} protected parameterLabel(k:string){return({longitud:'Longitud (m)',diametroPunta:'Diámetro punta (mm)',conicidad:'Conicidad (mm/m)',recubrimiento:'Recubrimiento (mm)',pasoEspiral:'Paso espiral (m)'}as Record<string,string>)[k]??k;}
 protected closeEditor(){this.editor.set(null);this.error.set('');}
 protected newResource(){this.resourceDraft.set({id:this.state.nextId('r'),code:'',name:'',type:'material',unit:'kg',currentCost:0,previousCost:0,effectiveFrom:new Date().toISOString().slice(0,10)});this.editor.set('resource');} protected editResource(r:CostResource){this.resourceDraft.set(structuredClone(r));this.editor.set('resource');} protected saveResource(){const d=this.resourceDraft();if(!d?.code.trim()||!d.name.trim()||d.currentCost<0)return this.error.set('Completa código, nombre y costo.');if(!d.previousCost)d.previousCost=d.currentCost;this.state.saveResource(d);this.closeEditor();}
 protected newPart(){this.partDraft.set({id:this.state.nextId('p'),code:'',name:'',lines:[]});this.editor.set('part');} protected editPart(x:CostPart){this.partDraft.set(structuredClone(x));this.editor.set('part');} protected addLine(){this.partDraft.update(d=>d?({...d,lines:[...d.lines,{resourceId:this.state.resources()[0]?.id??'',quantity:1,wastePct:0}]}):d);} protected removeLine(i:number){this.partDraft.update(d=>d?({...d,lines:d.lines.filter((_,n)=>n!==i)}):d);} protected savePart(){const d=this.partDraft();if(!d?.code.trim()||!d.name.trim()||!d.lines.length)return this.error.set('La partida requiere código, nombre y al menos un recurso.');this.state.savePart(d);this.closeEditor();}
 protected newTemplate(){this.templateDraft.set({id:this.state.nextId('t'),code:'',name:'',family:'',partIds:[]});this.editor.set('template');} protected editTemplate(x:CostTemplate){this.templateDraft.set(structuredClone(x));this.editor.set('template');} protected togglePart(id:string,on:boolean){this.templateDraft.update(d=>d?({...d,partIds:on?[...new Set([...d.partIds,id])]:d.partIds.filter(x=>x!==id)}):d);} protected saveTemplate(){const d=this.templateDraft();if(!d?.code.trim()||!d.name.trim()||!d.partIds.length)return this.error.set('La plantilla requiere código, nombre y al menos una partida.');this.state.saveTemplate(d);this.closeEditor();}
 protected newProduct(){this.productDraft.set({id:this.state.nextId('cp'),code:'',name:'',templateId:this.state.templates()[0]?.id??'',version:'V01',unit:'UND',parameters:{longitud:7,diametroPunta:120,conicidad:15,recubrimiento:15,pasoEspiral:0.08},quantityFactors:{},minMarkupPct:15,targetMarkupPct:25,maxMarkupPct:40});this.editor.set('product');} protected editProduct(x:CostProduct){this.productDraft.set(structuredClone(x));this.editor.set('product');} protected duplicateProduct(x:CostProduct){const d=structuredClone(x);d.id=this.state.nextId('cp');d.code=x.code+'-COPIA';d.name=x.name+' (copia)';d.version='V01';this.productDraft.set(d);this.editor.set('product');} protected setParam(k:string,v:number){this.productDraft.update(d=>d?({...d,parameters:{...d.parameters,[k]:v}}):d);} protected setFactor(id:string,v:number){this.productDraft.update(d=>d?({...d,quantityFactors:{...(d.quantityFactors??{}),[id]:v}}):d);} protected saveProduct(){const d=this.productDraft();if(!d?.code.trim()||!d.name.trim()||!d.templateId)return this.error.set('Completa código, nombre y plantilla.');this.state.saveProduct(d);this.closeEditor();}
 protected delResource(id:string){if(!confirm('¿Eliminar recurso?'))return;if(!this.state.deleteResource(id))alert('No se puede eliminar: el recurso está usado en una partida.');} protected delPart(id:string){if(!confirm('¿Eliminar partida?'))return;if(!this.state.deletePart(id))alert('No se puede eliminar: la partida está usada en una plantilla.');} protected delTemplate(id:string){if(!confirm('¿Eliminar plantilla?'))return;if(!this.state.deleteTemplate(id))alert('No se puede eliminar: la plantilla está usada por un producto.');} protected delProduct(id:string){if(confirm('¿Eliminar producto costeado?'))this.state.deleteProduct(id);}
}
