import { Routes } from '@angular/router';

export const PRODUCTION_ROUTES: Routes = [
  { path: '', pathMatch: 'full', redirectTo: 'dashboard' },
  { path: 'dashboard', loadComponent: () => import('./dashboard/dashboard').then((m) => m.ProductionDashboard) },
  { path: 'work-sheets', loadComponent: () => import('./work-sheets/work-sheet-list/work-sheet-list').then((m) => m.WorkSheetList) },
  { path: 'work-sheets/:id', loadComponent: () => import('./work-sheets/work-sheet-detail/work-sheet-detail').then((m) => m.WorkSheetDetail) },
  { path: 'planning', loadComponent: () => import('./planning/planning').then((m) => m.Planning) },
  { path: 'products', loadComponent: () => import('./products/product-list/product-list').then((m) => m.ProductList) },
  { path: 'products/new', loadComponent: () => import('./products/product-create/product-create').then((m) => m.ProductCreate) },
  { path: 'products/:id', loadComponent: () => import('./products/product-detail/product-detail').then((m) => m.ProductDetail) },
  { path: 'products/:id/edit', loadComponent: () => import('./products/product-create/product-create').then((m) => m.ProductCreate) },
  { path: 'bill-of-materials', loadComponent: () => import('./bill-of-materials/bom-list/bom-list').then((m) => m.BomList) },
  { path: 'bill-of-materials/new', loadComponent: () => import('./bill-of-materials/bom-create/bom-create').then((m) => m.BomCreate) },
  { path: 'bill-of-materials/:id', loadComponent: () => import('./bill-of-materials/bom-detail/bom-detail').then((m) => m.BomDetail) },
  { path: 'molds', loadComponent: () => import('./resources/mold-list/mold-list').then((m) => m.MoldList) },
  { path: 'molds/new', loadComponent: () => import('./resources/mold-create/mold-create').then((m) => m.MoldCreate) },
  { path: 'molds/:id', loadComponent: () => import('./resources/mold-detail/mold-detail').then((m) => m.MoldDetail) },
  { path: 'molds/:id/edit', loadComponent: () => import('./resources/mold-create/mold-create').then((m) => m.MoldCreate) },
  { path: 'machines', loadComponent: () => import('./resources/machine-list/machine-list').then((m) => m.MachineList) },
  { path: 'machines/new', loadComponent: () => import('./resources/machine-create/machine-create').then((m) => m.MachineCreate) },
  { path: 'machines/:id', loadComponent: () => import('./resources/machine-detail/machine-detail').then((m) => m.MachineDetail) },
  { path: 'machines/:id/edit', loadComponent: () => import('./resources/machine-create/machine-create').then((m) => m.MachineCreate) },
  { path: 'work-centers', loadComponent: () => import('./resources/work-center-list/work-center-list').then((m) => m.WorkCenterList) },
  { path: 'work-centers/new', loadComponent: () => import('./resources/work-center-create/work-center-create').then((m) => m.WorkCenterCreate) },
  { path: 'work-centers/:id', loadComponent: () => import('./resources/work-center-detail/work-center-detail').then((m) => m.WorkCenterDetail) },
  { path: 'work-centers/:id/edit', loadComponent: () => import('./resources/work-center-create/work-center-create').then((m) => m.WorkCenterCreate) },
  { path: 'quality/protocols', loadComponent: () => import('./quality/protocol-list/protocol-list').then((m) => m.ProtocolList) },
  { path: 'quality/protocols/new', loadComponent: () => import('./quality/protocol-create/protocol-create').then((m) => m.ProtocolCreate) },
  { path: 'quality/protocols/:id', loadComponent: () => import('./quality/protocol-detail/protocol-detail').then((m) => m.ProtocolDetail) },
  { path: 'quality/protocols/:id/edit', loadComponent: () => import('./quality/protocol-create/protocol-create').then((m) => m.ProtocolCreate) },
  { path: 'quality/inspections', loadComponent: () => import('./quality/inspection-list/inspection-list').then((m) => m.InspectionList) },
  { path: 'quality/inspections/new', loadComponent: () => import('./quality/inspection-create/inspection-create').then((m) => m.InspectionCreate) },
  { path: 'quality/inspections/:id', loadComponent: () => import('./quality/inspection-detail/inspection-detail').then((m) => m.InspectionDetail) },
  { path: 'output-bundles', loadComponent: () => import('./output-bundles/output-bundle-list/output-bundle-list').then((m) => m.OutputBundleList) },
  { path: 'output-bundles/:id', loadComponent: () => import('./output-bundles/output-bundle-detail/output-bundle-detail').then((m) => m.OutputBundleDetail) },
];
