import { Item } from '@core/models';

/** Seeded from the real CCP catalog extract (Articulos.xls / ReporteStock.xls). Codes, descriptions and units are real. */
export const ITEMS: Item[] = [
  // Materias primas — agregados
  { id: 'MP00001', code: 'MP00001', description: 'POLVILLO', category: 'raw_material', group: 'AGREGADOS', unitOfMeasure: 'M3', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 30, maxStock: 200, reorderPoint: 50, standardCost: 52, lastCost: 52, averageCost: 51.5, currency: 'PEN', suppliers: [{ supplierId: 'SUP-004', price: 52, currency: 'PEN', leadTimeDays: 2, isPrimary: true }], active: true },
  { id: 'MP00002', code: 'MP00002', description: 'PIEDRA HUSO 67', category: 'raw_material', group: 'AGREGADOS', unitOfMeasure: 'M3', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 30, maxStock: 220, reorderPoint: 55, standardCost: 54, lastCost: 55, averageCost: 54.2, currency: 'PEN', suppliers: [{ supplierId: 'SUP-004', price: 55, currency: 'PEN', leadTimeDays: 2, isPrimary: true }, { supplierId: 'SUP-005', price: 53, currency: 'PEN', leadTimeDays: 3, isPrimary: false }], active: true },
  { id: 'MP00003', code: 'MP00003', description: 'ARENA GRUESA', category: 'raw_material', group: 'AGREGADOS', unitOfMeasure: 'M3', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 25, maxStock: 180, reorderPoint: 45, standardCost: 50, lastCost: 51, averageCost: 50.4, currency: 'PEN', suppliers: [{ supplierId: 'SUP-005', price: 51, currency: 'PEN', leadTimeDays: 2, isPrimary: true }], active: true },
  { id: 'MP00004', code: 'MP00004', description: 'ARENA FINA', category: 'raw_material', group: 'AGREGADOS', unitOfMeasure: 'M3', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 20, maxStock: 150, reorderPoint: 40, standardCost: 51, lastCost: 50, averageCost: 50.6, currency: 'PEN', suppliers: [{ supplierId: 'SUP-005', price: 50, currency: 'PEN', leadTimeDays: 2, isPrimary: true }], active: true },
  { id: 'MP00005', code: 'MP00005', description: 'CONFITILLO', category: 'raw_material', group: 'AGREGADOS', unitOfMeasure: 'M3', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 10, maxStock: 90, reorderPoint: 20, standardCost: 53, lastCost: 53, averageCost: 53, currency: 'PEN', suppliers: [{ supplierId: 'SUP-004', price: 53, currency: 'PEN', leadTimeDays: 2, isPrimary: true }], active: true },

  // Materias primas — cemento (lote por partida de producción)
  { id: 'MP00006', code: 'MP00006', description: 'CEMENTO CEMEX PORTLAND TIPO I', category: 'raw_material', group: 'CEMENTO', unitOfMeasure: 'BOL', tracksLot: true, tracksExpiration: false, outboundStrategy: 'FIFO', minStock: 400, maxStock: 3000, reorderPoint: 800, standardCost: 21.5, lastCost: 22, averageCost: 21.7, currency: 'PEN', suppliers: [{ supplierId: 'SUP-011', price: 22, currency: 'PEN', leadTimeDays: 3, isPrimary: true }], active: true },
  { id: 'MP00007', code: 'MP00007', description: 'CEMENTO CEMEX ANTISALITRE HS', category: 'raw_material', group: 'CEMENTO', unitOfMeasure: 'BOL', tracksLot: true, tracksExpiration: false, outboundStrategy: 'FIFO', minStock: 100, maxStock: 1200, reorderPoint: 250, standardCost: 22.8, lastCost: 23, averageCost: 22.9, currency: 'PEN', suppliers: [{ supplierId: 'SUP-011', price: 23, currency: 'PEN', leadTimeDays: 3, isPrimary: true }], active: true },
  { id: 'MP00008', code: 'MP00008', description: 'CEMENTO SOL PORTLAND TIPO I', category: 'raw_material', group: 'CEMENTO', unitOfMeasure: 'BOL', tracksLot: true, tracksExpiration: false, outboundStrategy: 'FIFO', minStock: 200, maxStock: 1500, reorderPoint: 400, standardCost: 20.9, lastCost: 21, averageCost: 20.9, currency: 'PEN', suppliers: [{ supplierId: 'SUP-012', price: 21, currency: 'PEN', leadTimeDays: 3, isPrimary: true }], active: true },
  { id: 'MP00009', code: 'MP00009', description: 'CEMENTO ANDINO PORTLAND TIPO V', category: 'raw_material', group: 'CEMENTO', unitOfMeasure: 'BOL', tracksLot: true, tracksExpiration: false, outboundStrategy: 'FIFO', minStock: 150, maxStock: 1200, reorderPoint: 300, standardCost: 21.8, lastCost: 22, averageCost: 21.9, currency: 'PEN', suppliers: [{ supplierId: 'SUP-012', price: 22, currency: 'PEN', leadTimeDays: 3, isPrimary: true }], active: true },
  { id: 'MP00039', code: 'MP00039', description: 'CEMENTO ANDINO ULTRA TIPO HS - ANTISALITRE', category: 'raw_material', group: 'CEMENTO', unitOfMeasure: 'BOL', tracksLot: true, tracksExpiration: false, outboundStrategy: 'FIFO', minStock: 80, maxStock: 900, reorderPoint: 200, standardCost: 23.1, lastCost: 23.5, averageCost: 23.2, currency: 'PEN', suppliers: [{ supplierId: 'SUP-012', price: 23.5, currency: 'PEN', leadTimeDays: 4, isPrimary: true }], active: true },

  // Materias primas — fierro corrugado
  { id: 'MP00010', code: 'MP00010', description: 'BA-CO ASTM A615 GRADO 60 DE 6 MM (1/4") X 9 MTS', category: 'raw_material', group: 'FIERRO', unitOfMeasure: 'UND', tracksLot: true, tracksExpiration: false, outboundStrategy: 'FIFO', minStock: 500, maxStock: 5000, reorderPoint: 1200, standardCost: 5.4, lastCost: 5.6, averageCost: 5.5, currency: 'PEN', suppliers: [{ supplierId: 'SUP-013', price: 5.6, currency: 'PEN', leadTimeDays: 5, isPrimary: true }], active: true },
  { id: 'MP00011', code: 'MP00011', description: 'BA-CO ASTM A615 GRADO 60 DE 12 MM X 9 MTS', category: 'raw_material', group: 'FIERRO', unitOfMeasure: 'UND', tracksLot: true, tracksExpiration: false, outboundStrategy: 'FIFO', minStock: 800, maxStock: 6000, reorderPoint: 1800, standardCost: 15.9, lastCost: 16.3, averageCost: 16.1, currency: 'PEN', suppliers: [{ supplierId: 'SUP-013', price: 16.3, currency: 'PEN', leadTimeDays: 5, isPrimary: true }, { supplierId: 'SUP-014', price: 16.1, currency: 'PEN', leadTimeDays: 6, isPrimary: false }], active: true },
  { id: 'MP00012', code: 'MP00012', description: 'BA-CO ASTM A615 GRADO 60 DE 3/8" X 9 MTS', category: 'raw_material', group: 'FIERRO', unitOfMeasure: 'UND', tracksLot: true, tracksExpiration: false, outboundStrategy: 'FIFO', minStock: 400, maxStock: 4000, reorderPoint: 900, standardCost: 12.1, lastCost: 12.4, averageCost: 12.3, currency: 'PEN', suppliers: [{ supplierId: 'SUP-013', price: 12.4, currency: 'PEN', leadTimeDays: 5, isPrimary: true }], active: true },
  { id: 'MP00013', code: 'MP00013', description: 'BA-CO ASTM A615 GRADO 60 DE 1/2" X 9 MTS', category: 'raw_material', group: 'FIERRO', unitOfMeasure: 'UND', tracksLot: true, tracksExpiration: false, outboundStrategy: 'FIFO', minStock: 300, maxStock: 3500, reorderPoint: 800, standardCost: 16.8, lastCost: 17, averageCost: 16.9, currency: 'PEN', suppliers: [{ supplierId: 'SUP-013', price: 17, currency: 'PEN', leadTimeDays: 5, isPrimary: true }], active: true },
  { id: 'MP00014', code: 'MP00014', description: 'BA-CO ASTM A615 GRADO 60 DE 5/8" X 9 MTS', category: 'raw_material', group: 'FIERRO', unitOfMeasure: 'UND', tracksLot: true, tracksExpiration: false, outboundStrategy: 'FIFO', minStock: 200, maxStock: 2500, reorderPoint: 600, standardCost: 3120, lastCost: 3150, averageCost: 3135, currency: 'PEN', suppliers: [{ supplierId: 'SUP-013', price: 3150, currency: 'PEN', leadTimeDays: 6, isPrimary: true }], active: true },
  { id: 'MP00015', code: 'MP00015', description: 'BA-CO ASTM A615 GRADO 60 DE 3/4" X 9 MTS', category: 'raw_material', group: 'FIERRO', unitOfMeasure: 'UND', tracksLot: true, tracksExpiration: false, outboundStrategy: 'FIFO', minStock: 150, maxStock: 2000, reorderPoint: 500, standardCost: 3080, lastCost: 3100, averageCost: 3090, currency: 'PEN', suppliers: [{ supplierId: 'SUP-013', price: 3100, currency: 'PEN', leadTimeDays: 6, isPrimary: true }], active: true },
  { id: 'MP00034', code: 'MP00034', description: 'BA-CO JIS G3532/ASTM A496 DE 4.7 MM X 8.80 MTS', category: 'raw_material', group: 'FIERRO', unitOfMeasure: 'UND', tracksLot: true, tracksExpiration: false, outboundStrategy: 'FIFO', minStock: 500, maxStock: 5000, reorderPoint: 1200, standardCost: 5.1, lastCost: 5.2, averageCost: 5.15, currency: 'PEN', suppliers: [{ supplierId: 'SUP-014', price: 5.2, currency: 'PEN', leadTimeDays: 5, isPrimary: true }], active: true },

  // Materias primas — alambres
  { id: 'MP00016', code: 'MP00016', description: 'ALAMBRE RECOCIDO # 16', category: 'raw_material', group: 'ALAMBRES', unitOfMeasure: 'KG', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 500, maxStock: 4000, reorderPoint: 1000, standardCost: 2.6, lastCost: 2.7, averageCost: 2.65, currency: 'PEN', suppliers: [{ supplierId: 'SUP-014', price: 2.7, currency: 'PEN', leadTimeDays: 4, isPrimary: true }], active: true },
  { id: 'MP00017', code: 'MP00017', description: 'ALAMBRE TREFILADO # 12 (2.7 MM)', category: 'raw_material', group: 'ALAMBRES', unitOfMeasure: 'KG', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 500, maxStock: 4000, reorderPoint: 1000, standardCost: 2.1, lastCost: 2.15, averageCost: 2.12, currency: 'PEN', suppliers: [{ supplierId: 'SUP-014', price: 2.15, currency: 'PEN', leadTimeDays: 4, isPrimary: true }], active: true },
  { id: 'MP00018', code: 'MP00018', description: 'ALAMBRE TREFILADO # 14 (2.0 MM)', category: 'raw_material', group: 'ALAMBRES', unitOfMeasure: 'KG', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 400, maxStock: 3500, reorderPoint: 900, standardCost: 1.85, lastCost: 1.9, averageCost: 1.88, currency: 'PEN', suppliers: [{ supplierId: 'SUP-014', price: 1.9, currency: 'PEN', leadTimeDays: 4, isPrimary: true }], active: true },
  { id: 'MP00019', code: 'MP00019', description: 'ALAMBRON DE TREFILERIA DE 5.5 MM C/CROMO', category: 'raw_material', group: 'ALAMBRES', unitOfMeasure: 'KG', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 300, maxStock: 2500, reorderPoint: 700, standardCost: 2.4, lastCost: 2.45, averageCost: 2.42, currency: 'PEN', suppliers: [{ supplierId: 'SUP-014', price: 2.45, currency: 'PEN', leadTimeDays: 4, isPrimary: true }], active: true },

  // Materias primas — tubería PVC (materiales auxiliares)
  { id: 'MA00031', code: 'MA00031', description: 'TUBO PVC ID 5/8" (20MM) X 5MT CLASE 10 COLOR NEGRO', category: 'raw_material', group: 'TUBOS PVC', unitOfMeasure: 'UND', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 100, maxStock: 600, reorderPoint: 200, standardCost: 3.6, lastCost: 3.7, averageCost: 3.65, currency: 'PEN', suppliers: [{ supplierId: 'SUP-006', price: 3.7, currency: 'PEN', leadTimeDays: 3, isPrimary: true }], active: true },
  { id: 'MA00032', code: 'MA00032', description: 'TUBO PVC ID 3/4" (22MM) X 5MT CLASE 10 COLOR NEGRO', category: 'raw_material', group: 'TUBOS PVC', unitOfMeasure: 'UND', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 100, maxStock: 550, reorderPoint: 180, standardCost: 4.2, lastCost: 4.3, averageCost: 4.25, currency: 'PEN', suppliers: [{ supplierId: 'SUP-006', price: 4.3, currency: 'PEN', leadTimeDays: 3, isPrimary: true }], active: true },
  { id: 'MA00033', code: 'MA00033', description: 'TUBO PVC ID 1-1/4" (40MM) X 5MT CLA-10 COLOR NEGRO', category: 'raw_material', group: 'TUBOS PVC', unitOfMeasure: 'UND', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 60, maxStock: 400, reorderPoint: 120, standardCost: 8.1, lastCost: 8.4, averageCost: 8.2, currency: 'PEN', suppliers: [{ supplierId: 'SUP-006', price: 8.4, currency: 'PEN', leadTimeDays: 3, isPrimary: true }], active: true },

  // Suministros — soldadura
  { id: 'MA00001', code: 'MA00001', description: 'ELECTRODO 6011 5/32" (4.00 MM) SOLDITEC', category: 'supply', group: 'SOLDADURA', unitOfMeasure: 'KG', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 40, maxStock: 300, reorderPoint: 80, standardCost: 12.5, lastCost: 12.8, averageCost: 12.6, currency: 'PEN', suppliers: [{ supplierId: 'SUP-016', price: 12.8, currency: 'PEN', leadTimeDays: 4, isPrimary: true }], active: true },
  { id: 'MA00024', code: 'MA00024', description: 'ELECTRODO 6011 1/8" (3.25 MM) CELLOCORD', category: 'supply', group: 'SOLDADURA', unitOfMeasure: 'KG', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 40, maxStock: 300, reorderPoint: 80, standardCost: 11.9, lastCost: 12.1, averageCost: 12, currency: 'PEN', suppliers: [{ supplierId: 'SUP-016', price: 12.1, currency: 'PEN', leadTimeDays: 4, isPrimary: true }], active: true },
  { id: 'MA00025', code: 'MA00025', description: 'ELECTRODO 7018 1/8" (3.25 MM) SUPERCITO', category: 'supply', group: 'SOLDADURA', unitOfMeasure: 'KG', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 30, maxStock: 250, reorderPoint: 70, standardCost: 13.4, lastCost: 13.6, averageCost: 13.5, currency: 'PEN', suppliers: [{ supplierId: 'SUP-016', price: 13.6, currency: 'PEN', leadTimeDays: 4, isPrimary: true }], active: true },
  { id: 'MA00054', code: 'MA00054', description: 'ELECTRODO S-6011.D 1/8" (3.2 MM X 350 MM) HYUNDAI', category: 'supply', group: 'SOLDADURA', unitOfMeasure: 'KG', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 20, maxStock: 200, reorderPoint: 50, standardCost: 12.2, lastCost: 12.4, averageCost: 12.3, currency: 'PEN', suppliers: [{ supplierId: 'SUP-016', price: 12.4, currency: 'PEN', leadTimeDays: 4, isPrimary: true }], active: true },
  { id: 'MA00040', code: 'MA00040', description: 'OXIGENO', category: 'supply', group: 'SOLDADURA', unitOfMeasure: 'M3', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 5, maxStock: 40, reorderPoint: 10, standardCost: 18, lastCost: 18.5, averageCost: 18.2, currency: 'PEN', suppliers: [{ supplierId: 'SUP-016', price: 18.5, currency: 'PEN', leadTimeDays: 3, isPrimary: true }], active: true },

  // Suministros — sellador/químicos
  { id: 'MA00002', code: 'MA00002', description: 'CHEMA ALQUITRAN', category: 'supply', group: 'SELLADORES', unitOfMeasure: 'GAL', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 10, maxStock: 80, reorderPoint: 20, standardCost: 45, lastCost: 46, averageCost: 45.4, currency: 'PEN', suppliers: [{ supplierId: 'SUP-015', price: 46, currency: 'PEN', leadTimeDays: 5, isPrimary: true }], active: true },
  { id: 'MA00003', code: 'MA00003', description: 'SELLADOR 415', category: 'supply', group: 'SELLADORES', unitOfMeasure: 'GAL', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 8, maxStock: 60, reorderPoint: 15, standardCost: 118, lastCost: 122, averageCost: 119.5, currency: 'PEN', suppliers: [{ supplierId: 'SUP-015', price: 122, currency: 'PEN', leadTimeDays: 5, isPrimary: true }], active: true },
  { id: 'SU00256', code: 'SU00256', description: 'CATALIZADOR EPOXICO TITANIC', category: 'supply', group: 'SELLADORES', unitOfMeasure: 'GAL', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 4, maxStock: 30, reorderPoint: 8, standardCost: 42, lastCost: 44, averageCost: 43, currency: 'PEN', suppliers: [{ supplierId: 'SUP-015', price: 44, currency: 'PEN', leadTimeDays: 5, isPrimary: true }], active: true },

  // Suministros — ferretería / EPP
  { id: 'MA00004', code: 'MA00004', description: 'ARANDELA PLANA 1"', category: 'supply', group: 'FERRETERIA', unitOfMeasure: 'UND', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 100, maxStock: 1000, reorderPoint: 200, standardCost: 0.35, lastCost: 0.36, averageCost: 0.35, currency: 'PEN', suppliers: [{ supplierId: 'SUP-003', price: 0.36, currency: 'PEN', leadTimeDays: 3, isPrimary: true }], active: true },
  { id: 'MA00022', code: 'MA00022', description: 'CAL DE OBRA', category: 'supply', group: 'FERRETERIA', unitOfMeasure: 'BOL', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 10, maxStock: 100, reorderPoint: 25, standardCost: 12, lastCost: 12.5, averageCost: 12.2, currency: 'PEN', suppliers: [{ supplierId: 'SUP-006', price: 12.5, currency: 'PEN', leadTimeDays: 4, isPrimary: true }], active: true },
  { id: 'SU00065', code: 'SU00065', description: 'DISCO DE CORTE 4-1/2" X 3/64" X 7/8"', category: 'supply', group: 'FERRETERIA', unitOfMeasure: 'UND', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 30, maxStock: 200, reorderPoint: 60, standardCost: 4.8, lastCost: 5, averageCost: 4.9, currency: 'PEN', suppliers: [{ supplierId: 'SUP-003', price: 5, currency: 'PEN', leadTimeDays: 3, isPrimary: true }], active: true },
  { id: 'SU00069', code: 'SU00069', description: 'DISCO FLAP', category: 'supply', group: 'FERRETERIA', unitOfMeasure: 'UND', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 20, maxStock: 150, reorderPoint: 40, standardCost: 6.2, lastCost: 6.5, averageCost: 6.3, currency: 'PEN', suppliers: [{ supplierId: 'SUP-003', price: 6.5, currency: 'PEN', leadTimeDays: 3, isPrimary: true }], active: true },
  { id: 'SU00096', code: 'SU00096', description: 'BOTA DE JEBE PUNTA DE ACERO PLANTA AMARILLA', category: 'supply', group: 'EPP', unitOfMeasure: 'PAR', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 5, maxStock: 40, reorderPoint: 10, standardCost: 38, lastCost: 39, averageCost: 38.5, currency: 'PEN', suppliers: [{ supplierId: 'SUP-006', price: 39, currency: 'PEN', leadTimeDays: 5, isPrimary: true }], active: true },
  { id: 'SU00284', code: 'SU00284', description: 'GUANTE DE JEBE CALIBRE 25 DE 12" T-8 PROTEX', category: 'supply', group: 'EPP', unitOfMeasure: 'UND', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 10, maxStock: 60, reorderPoint: 20, standardCost: 22, lastCost: 23, averageCost: 22.4, currency: 'PEN', suppliers: [{ supplierId: 'SUP-006', price: 23, currency: 'PEN', leadTimeDays: 4, isPrimary: true }], active: true },

  // Suministros — moldes / repuestos planta
  { id: 'SU00786', code: 'SU00786', description: 'RUEDA P/MOLDE DE POSTE 9 MTS LONGITUD', category: 'supply', group: 'REPUESTOS MOLDE', unitOfMeasure: 'UND', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 2, maxStock: 20, reorderPoint: 5, standardCost: 340, lastCost: 355, averageCost: 347, currency: 'USD', suppliers: [{ supplierId: 'SUP-018', price: 95, currency: 'USD', leadTimeDays: 45, isPrimary: true }], active: true },
  { id: 'SU01064', code: 'SU01064', description: 'BRIDA P/POSTE DE 13/400/180/375', category: 'supply', group: 'REPUESTOS MOLDE', unitOfMeasure: 'UND', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 3, maxStock: 25, reorderPoint: 6, standardCost: 210, lastCost: 220, averageCost: 214, currency: 'PEN', suppliers: [{ supplierId: 'SUP-018', price: 220, currency: 'PEN', leadTimeDays: 30, isPrimary: true }], active: true },
  { id: 'SU01427', code: 'SU01427', description: 'BRIDA P/POSTE C.A.C DE 15/400/2/210/435', category: 'supply', group: 'REPUESTOS MOLDE', unitOfMeasure: 'UND', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 2, maxStock: 20, reorderPoint: 5, standardCost: 245, lastCost: 250, averageCost: 247, currency: 'PEN', suppliers: [{ supplierId: 'SUP-018', price: 250, currency: 'PEN', leadTimeDays: 30, isPrimary: true }], active: true },
  { id: 'SU01122', code: 'SU01122', description: 'BASE PORTAFUSIBLE P/POSTE DE CONCRETO', category: 'supply', group: 'ACCESORIOS POSTE', unitOfMeasure: 'UND', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 20, maxStock: 150, reorderPoint: 40, standardCost: 18, lastCost: 19, averageCost: 18.4, currency: 'PEN', suppliers: [{ supplierId: 'SUP-003', price: 19, currency: 'PEN', leadTimeDays: 6, isPrimary: true }], active: true },
  { id: 'SU00653', code: 'SU00653', description: 'CRUCETA 2"', category: 'supply', group: 'ACCESORIOS POSTE', unitOfMeasure: 'PAQ', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 15, maxStock: 100, reorderPoint: 30, standardCost: 27, lastCost: 28, averageCost: 27.4, currency: 'PEN', suppliers: [{ supplierId: 'SUP-003', price: 28, currency: 'PEN', leadTimeDays: 6, isPrimary: true }], active: true },
  { id: 'SU00514', code: 'SU00514', description: 'PLACA EN BAJO RELIEVE 8/400/2/180/300', category: 'supply', group: 'ACCESORIOS POSTE', unitOfMeasure: 'UND', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 10, maxStock: 80, reorderPoint: 20, standardCost: 15, lastCost: 15.5, averageCost: 15.2, currency: 'PEN', suppliers: [{ supplierId: 'SUP-003', price: 15.5, currency: 'PEN', leadTimeDays: 6, isPrimary: true }], active: true },

  // Suministros varios operativos
  { id: 'SU00001', code: 'SU00001', description: 'TRAPO INDUSTRIAL', category: 'supply', group: 'LIMPIEZA', unitOfMeasure: 'KG', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 10, maxStock: 80, reorderPoint: 20, standardCost: 6.5, lastCost: 6.8, averageCost: 6.6, currency: 'PEN', suppliers: [{ supplierId: 'SUP-006', price: 6.8, currency: 'PEN', leadTimeDays: 3, isPrimary: true }], active: true },
  { id: 'SU00130', code: 'SU00130', description: 'CINTA TEFLON 1/2" ANCHO X 7 MTS LG', category: 'supply', group: 'FERRETERIA', unitOfMeasure: 'UND', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 40, maxStock: 300, reorderPoint: 80, standardCost: 1.2, lastCost: 1.3, averageCost: 1.25, currency: 'PEN', suppliers: [{ supplierId: 'SUP-006', price: 1.3, currency: 'PEN', leadTimeDays: 3, isPrimary: true }], active: true },
  { id: 'SU00397', code: 'SU00397', description: 'PINCEL', category: 'supply', group: 'FERRETERIA', unitOfMeasure: 'UND', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 15, maxStock: 100, reorderPoint: 25, standardCost: 3.5, lastCost: 3.7, averageCost: 3.6, currency: 'PEN', suppliers: [{ supplierId: 'SUP-006', price: 3.7, currency: 'PEN', leadTimeDays: 3, isPrimary: true }], active: true },
  { id: 'SU00285', code: 'SU00285', description: 'GASOLINA', category: 'supply', group: 'COMBUSTIBLES', unitOfMeasure: 'GAL', tracksLot: false, tracksExpiration: false, outboundStrategy: 'NONE', minStock: 10, maxStock: 60, reorderPoint: 20, standardCost: 16.5, lastCost: 17, averageCost: 16.7, currency: 'PEN', suppliers: [{ supplierId: 'SUP-006', price: 17, currency: 'PEN', leadTimeDays: 2, isPrimary: true }], active: true },

  // Productos terminados (agrupados como MP en el archivo fuente, retagged para el prototipo)
  { id: 'MP00046', code: 'MP00046', description: 'POSTE CAC 9/200/2/140/275 INCLUYE PERILLA PROTECCION', category: 'finished_good', group: 'POSTES', unitOfMeasure: 'UND', tracksLot: true, tracksExpiration: false, outboundStrategy: 'FIFO', minStock: 20, maxStock: 200, reorderPoint: 40, standardCost: 285, lastCost: 290, averageCost: 287, currency: 'PEN', suppliers: [], active: true },
  { id: 'MP00047', code: 'MP00047', description: 'DUCTO DE CONCRETO DE 4 VIAS C/HUECO DE 90 MM', category: 'finished_good', group: 'DUCTOS', unitOfMeasure: 'UND', tracksLot: true, tracksExpiration: false, outboundStrategy: 'FIFO', minStock: 15, maxStock: 150, reorderPoint: 30, standardCost: 168, lastCost: 172, averageCost: 170, currency: 'PEN', suppliers: [], active: true },
  { id: 'MP00048', code: 'MP00048', description: 'DUCTO DE CONCRETO DE 2 VIAS C/HUECO DE 90 MM', category: 'finished_good', group: 'DUCTOS', unitOfMeasure: 'UND', tracksLot: true, tracksExpiration: false, outboundStrategy: 'FIFO', minStock: 15, maxStock: 150, reorderPoint: 30, standardCost: 112, lastCost: 115, averageCost: 113.5, currency: 'PEN', suppliers: [], active: true },
  { id: 'MP00049', code: 'MP00049', description: 'CAJA CUADRADA 40X40X30 C/TAPA LOGO CCP SAC', category: 'finished_good', group: 'CAJAS', unitOfMeasure: 'UND', tracksLot: true, tracksExpiration: false, outboundStrategy: 'FIFO', minStock: 10, maxStock: 120, reorderPoint: 25, standardCost: 95, lastCost: 98, averageCost: 96.5, currency: 'PEN', suppliers: [], active: true },
  { id: 'MP00050', code: 'MP00050', description: 'CAJA REDONDA P/PUESTO A TIERRA 396MMD C/TAPA Y ARO', category: 'finished_good', group: 'CAJAS', unitOfMeasure: 'UND', tracksLot: true, tracksExpiration: false, outboundStrategy: 'FIFO', minStock: 10, maxStock: 100, reorderPoint: 20, standardCost: 88, lastCost: 90, averageCost: 89, currency: 'PEN', suppliers: [], active: true },
];
