import { SalesOrder, SalesQuotation } from '@core/models';

export const SALES_QUOTATIONS: SalesQuotation[] = [
  {
    id: 'SQ-001',
    number: 'COT-2026-0301',
    customerId: 'CUST-001',
    customerName: 'Constructora Andina S.A.C.',
    status: 'accepted',
    currency: 'PEN',
    issuedAt: '2026-07-10',
    expiresAt: '2026-08-10',
    lines: [
      { productCode: 'PCC-9-200', description: 'Poste de concreto centrifugado 9m / 200 kgf', quantity: 60, unitOfMeasure: 'UND', unitPrice: 480 },
      { productCode: 'CRZ-2.4', description: 'Cruceta de concreto 2.4m', quantity: 60, unitOfMeasure: 'UND', unitPrice: 95 },
    ],
    total: 34500,
    opportunityId: 'OPP-014',
  },
  {
    id: 'SQ-002',
    number: 'COT-2026-0302',
    customerId: 'CUST-002',
    customerName: 'Electro Sur Distribución S.A.',
    status: 'sent',
    currency: 'PEN',
    issuedAt: '2026-08-05',
    expiresAt: '2026-09-05',
    lines: [
      { productCode: 'PCC-11-300', description: 'Poste de concreto centrifugado 11m / 300 kgf', quantity: 40, unitOfMeasure: 'UND', unitPrice: 720 },
      { productCode: 'ACC-AIS-P', description: 'Aislador de porcelana tipo pin', quantity: 160, unitOfMeasure: 'UND', unitPrice: 18 },
    ],
    total: 31680,
    opportunityId: 'OPP-021',
  },
  {
    id: 'SQ-003',
    number: 'COT-2026-0303',
    customerId: 'CUST-003',
    customerName: 'Municipalidad Provincial de Cañete',
    status: 'draft',
    currency: 'PEN',
    issuedAt: '2026-08-18',
    expiresAt: '2026-09-18',
    lines: [{ productCode: 'PCC-8-200', description: 'Poste de concreto centrifugado 8m / 200 kgf', quantity: 25, unitOfMeasure: 'UND', unitPrice: 410 }],
    total: 10250,
  },
  {
    id: 'SQ-004',
    number: 'COT-2026-0304',
    customerId: 'CUST-004',
    customerName: 'Inversiones Vial Norte E.I.R.L.',
    status: 'expired',
    currency: 'PEN',
    issuedAt: '2026-06-01',
    expiresAt: '2026-07-01',
    lines: [{ productCode: 'PCC-9-200', description: 'Poste de concreto centrifugado 9m / 200 kgf', quantity: 30, unitOfMeasure: 'UND', unitPrice: 480 }],
    total: 14400,
  },
  {
    id: 'SQ-005',
    number: 'COT-2026-0305',
    customerId: 'CUST-005',
    customerName: 'Hidrandina Distribución Eléctrica S.A.',
    status: 'rejected',
    currency: 'USD',
    issuedAt: '2026-07-22',
    expiresAt: '2026-08-22',
    lines: [
      { productCode: 'PCC-13-400', description: 'Poste de concreto centrifugado 13m / 400 kgf', quantity: 20, unitOfMeasure: 'UND', unitPrice: 310 },
      { productCode: 'ACC-ABZ-M', description: 'Abrazadera metálica para cruceta', quantity: 80, unitOfMeasure: 'UND', unitPrice: 6 },
    ],
    total: 6680,
  },
  {
    id: 'SQ-006',
    number: 'COT-2026-0306',
    customerId: 'CUST-006',
    customerName: 'Constructora Los Álamos S.R.L.',
    status: 'accepted',
    currency: 'PEN',
    issuedAt: '2026-08-01',
    expiresAt: '2026-09-01',
    lines: [
      { productCode: 'PCC-9-200', description: 'Poste de concreto centrifugado 9m / 200 kgf', quantity: 50, unitOfMeasure: 'UND', unitPrice: 480 },
      { productCode: 'CRZ-2.4', description: 'Cruceta de concreto 2.4m', quantity: 50, unitOfMeasure: 'UND', unitPrice: 95 },
      { productCode: 'ACC-PRN-G', description: 'Perno galvanizado 5/8" x 12"', quantity: 200, unitOfMeasure: 'UND', unitPrice: 4.5 },
    ],
    total: 29650,
    opportunityId: 'OPP-027',
  },
  {
    id: 'SQ-007',
    number: 'COT-2026-0307',
    customerId: 'CUST-007',
    customerName: 'Municipalidad Distrital de Pativilca',
    status: 'sent',
    currency: 'PEN',
    issuedAt: '2026-08-15',
    expiresAt: '2026-09-15',
    lines: [{ productCode: 'PCC-8-200', description: 'Poste de concreto centrifugado 8m / 200 kgf', quantity: 15, unitOfMeasure: 'UND', unitPrice: 410 }],
    total: 6150,
  },
  {
    id: 'SQ-008',
    number: 'COT-2026-0308',
    customerId: 'CUST-008',
    customerName: 'Distribuidora Eléctrica del Centro S.A.C.',
    status: 'draft',
    currency: 'PEN',
    issuedAt: '2026-08-20',
    expiresAt: '2026-09-20',
    lines: [
      { productCode: 'PCC-11-300', description: 'Poste de concreto centrifugado 11m / 300 kgf', quantity: 35, unitOfMeasure: 'UND', unitPrice: 720 },
      { productCode: 'ACC-AIS-P', description: 'Aislador de porcelana tipo pin', quantity: 140, unitOfMeasure: 'UND', unitPrice: 18 },
    ],
    total: 27720,
  },
  {
    id: 'SQ-009',
    number: 'COT-2026-0309',
    customerId: 'CUST-009',
    customerName: 'Consorcio Vial Chincha S.A.',
    status: 'accepted',
    currency: 'PEN',
    issuedAt: '2026-07-28',
    expiresAt: '2026-08-28',
    lines: [{ productCode: 'PCC-9-200', description: 'Poste de concreto centrifugado 9m / 200 kgf', quantity: 45, unitOfMeasure: 'UND', unitPrice: 480 }],
    total: 21600,
    opportunityId: 'OPP-033',
  },
];

export const SALES_ORDERS: SalesOrder[] = [
  {
    id: 'SO-001',
    number: 'PV-2026-0501',
    customerId: 'CUST-001',
    customerName: 'Constructora Andina S.A.C.',
    quotationId: 'SQ-001',
    status: 'invoiced',
    currency: 'PEN',
    confirmedAt: '2026-07-12',
    committedDeliveryDate: '2026-07-30',
    deliveryAddress: 'Km 45 Carretera Panamericana Sur, Cañete, Lima',
    lines: [
      { productCode: 'PCC-9-200', description: 'Poste de concreto centrifugado 9m / 200 kgf', quantity: 60, unitOfMeasure: 'UND', unitPrice: 480 },
      { productCode: 'CRZ-2.4', description: 'Cruceta de concreto 2.4m', quantity: 60, unitOfMeasure: 'UND', unitPrice: 95 },
    ],
    total: 34500,
  },
  {
    id: 'SO-002',
    number: 'PV-2026-0502',
    customerId: 'CUST-006',
    customerName: 'Constructora Los Álamos S.R.L.',
    quotationId: 'SQ-006',
    status: 'dispatched',
    currency: 'PEN',
    confirmedAt: '2026-08-03',
    committedDeliveryDate: '2026-08-25',
    deliveryAddress: 'Av. Industrial 890, Chincha Alta, Ica',
    lines: [
      { productCode: 'PCC-9-200', description: 'Poste de concreto centrifugado 9m / 200 kgf', quantity: 50, unitOfMeasure: 'UND', unitPrice: 480, unitCost: 356 },
      { productCode: 'CRZ-2.4', description: 'Cruceta de concreto 2.4m', quantity: 50, unitOfMeasure: 'UND', unitPrice: 95, unitCost: 62 },
      { productCode: 'ACC-PRN-G', description: 'Perno galvanizado 5/8" x 12"', quantity: 200, unitOfMeasure: 'UND', unitPrice: 4.5, unitCost: 2.8 },
    ],
    total: 29650,
    glosa: 'Suministro de postes y accesorios para obra de electrificación — Consorcio Vial Rutas del Sur.',
    workSheetId: 'HT-2026-0131',
    priceReview: { outcome: 'auto', reasons: [] },
    claimIds: ['SCL-001'],
  },
  {
    id: 'SO-003',
    number: 'PV-2026-0503',
    customerId: 'CUST-009',
    customerName: 'Consorcio Vial Chincha S.A.',
    quotationId: 'SQ-009',
    status: 'preparing',
    currency: 'PEN',
    confirmedAt: '2026-08-10',
    committedDeliveryDate: '2026-08-29',
    deliveryAddress: 'Ca. Los Pinos 234, Chincha Baja, Ica',
    lines: [{ productCode: 'PCC-9-200', description: 'Poste de concreto centrifugado 9m / 200 kgf', quantity: 45, unitOfMeasure: 'UND', unitPrice: 480 }],
    total: 21600,
  },
  {
    id: 'SO-004',
    number: 'PV-2026-0504',
    customerId: 'CUST-010',
    customerName: 'Electro Puno Distribución S.A.',
    status: 'confirmed',
    currency: 'PEN',
    confirmedAt: '2026-08-19',
    committedDeliveryDate: '2026-09-05',
    deliveryAddress: 'Jr. Tacna 512, Juliaca, Puno',
    lines: [
      { productCode: 'PCC-11-300', description: 'Poste de concreto centrifugado 11m / 300 kgf', quantity: 30, unitOfMeasure: 'UND', unitPrice: 720, unitCost: 612 },
      { productCode: 'ACC-AIS-P', description: 'Aislador de porcelana tipo pin', quantity: 120, unitOfMeasure: 'UND', unitPrice: 18, unitCost: 11 },
    ],
    total: 23760,
    glosa: 'Venta al contado — requiere OC del cliente y adelanto del 50%.',
    workSheetId: 'HT-2026-0140',
    paymentGate: {
      status: 'pending_collections',
      advancePct: 50,
      purchaseOrderDoc: { name: 'OC-ELPUNO-2026-118.pdf', uploadedAt: '2026-08-20' },
      advanceVoucher: { name: 'voucher-deposito-50pct.jpg', uploadedAt: '2026-08-21' },
    },
    priceReview: { outcome: 'needs_gerencia', reasons: ['Margen 12.4% por debajo del mínimo 18%.'] },
  },
  {
    id: 'SO-005',
    number: 'PV-2026-0505',
    customerId: 'CUST-011',
    customerName: 'Municipalidad Provincial de Barranca',
    status: 'preparing',
    currency: 'PEN',
    confirmedAt: '2026-08-15',
    committedDeliveryDate: '2026-09-02',
    deliveryAddress: 'Plaza de Armas s/n, Barranca, Lima',
    lines: [{ productCode: 'PCC-8-200', description: 'Poste de concreto centrifugado 8m / 200 kgf', quantity: 20, unitOfMeasure: 'UND', unitPrice: 410 }],
    total: 8200,
  },
  {
    id: 'SO-006',
    number: 'PV-2026-0506',
    customerId: 'CUST-012',
    customerName: 'Distribuidora Eléctrica Ica S.A.C.',
    status: 'dispatched',
    currency: 'PEN',
    confirmedAt: '2026-08-01',
    committedDeliveryDate: '2026-08-22',
    deliveryAddress: 'Av. Los Maestros 145, Ica',
    lines: [
      { productCode: 'PCC-13-400', description: 'Poste de concreto centrifugado 13m / 400 kgf', quantity: 18, unitOfMeasure: 'UND', unitPrice: 950, unitCost: 690 },
      { productCode: 'ACC-ABZ-M', description: 'Abrazadera metálica para cruceta', quantity: 72, unitOfMeasure: 'UND', unitPrice: 22, unitCost: 14 },
    ],
    total: 18684,
    workSheetId: 'HT-2026-0122',
    readyForDispatch: true,
    readyForDispatchAt: '2026-08-21',
    dispatchedAt: '2026-08-22',
    claimIds: ['SCL-002'],
  },
  {
    id: 'SO-007',
    number: 'PV-2026-0507',
    customerId: 'CUST-013',
    customerName: 'Constructora Vial del Sur S.A.C.',
    status: 'cancelled',
    currency: 'PEN',
    confirmedAt: '2026-07-25',
    committedDeliveryDate: '2026-08-12',
    deliveryAddress: 'Panamericana Sur Km 300, Ica',
    lines: [{ productCode: 'PCC-9-200', description: 'Poste de concreto centrifugado 9m / 200 kgf', quantity: 25, unitOfMeasure: 'UND', unitPrice: 480 }],
    total: 12000,
    notes: 'Cliente canceló por reprogramación de obra.',
  },
  {
    id: 'SO-008',
    number: 'PV-2026-0508',
    customerId: 'CUST-002',
    customerName: 'Electro Sur Distribución S.A.',
    status: 'invoiced',
    currency: 'PEN',
    confirmedAt: '2026-07-08',
    committedDeliveryDate: '2026-07-28',
    deliveryAddress: 'Av. Circunvalación 780, Arequipa',
    lines: [
      { productCode: 'PCC-11-300', description: 'Poste de concreto centrifugado 11m / 300 kgf', quantity: 42, unitOfMeasure: 'UND', unitPrice: 720 },
      { productCode: 'ACC-AIS-P', description: 'Aislador de porcelana tipo pin', quantity: 168, unitOfMeasure: 'UND', unitPrice: 18 },
    ],
    total: 33264,
  },
  {
    id: 'SO-009',
    number: 'PV-2026-0509',
    customerId: 'CUST-014',
    customerName: 'Municipalidad Distrital de Nazca',
    status: 'confirmed',
    currency: 'PEN',
    confirmedAt: '2026-08-21',
    committedDeliveryDate: '2026-09-10',
    deliveryAddress: 'Av. Los Incas 320, Nazca, Ica',
    lines: [{ productCode: 'PCC-8-200', description: 'Poste de concreto centrifugado 8m / 200 kgf', quantity: 22, unitOfMeasure: 'UND', unitPrice: 410 }],
    total: 9020,
  },
];
